name: 'Capawesome Cloud Live Update Action'
description: 'Deploy a live update to the Capawesome Cloud.'
author: 'Robin Genz <mail@robingenz.dev>'

# Define your inputs here.
inputs:
  appId:
    description: 'The Capawesome Cloud app ID.'
    required: true
  channel:
    description: 'The channel to deploy the bundle to.'
  commitMessage:
    description: 'The commit message of the Git commit that the bundle is linked to.'
  commitRef:
    description: 'The commit ref of the Git commit that the bundle is linked to.'
  commitSha:
    description: 'The commit SHA of the Git commit that the bundle is linked to.'
  path:
    description: 'The path to the bundle to upload. Must be a folder or zip archive.'
    required: true
  token:
    description: 'The Capawesome Cloud API token.'
    required: true

runs:
  using: node20
  main: dist/index.mjs
